### ISSUE TITLE
Estudar sobre o projeto Pong

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/siteFabrica#104]
- Estudar o projeto PONG 
    - controle: https://pong.fabsoftware.itp.ifsp.edu.br/ 
    - tela: https://pong.fabsoftware.itp.ifsp.edu.br/tela

- Tentar responder as perguntas: o que é? para que serve? como usar? Quais tecnologias utilizam? Ideia de melhorias? Problemas?
- Fazer uma apresentação sobre o que aprendeu para apresentar aos demais membros do grupo na próxima semana.

**Comment by MarcosFabSoftware** [comment]
Oque é? 
O projeto PONG é um jogo multiplayer onde se coloca duas pessoas, em celulares diferentes, para jogarem um contra o outro enquanto uma tela exibe a partida dos players. Utiliza-se da tecnologia de Socket.io para realizar a comunicação entre o cliente e um servidor, com baixa-latência

Para que serve?
Serve para se divertir e passar o tempo com o seu amigo ou inimigo. Utilizando-se de um jogo competitivo e inofensivo para isso

Como usar?
Primeiramente deve-se se acessar a aba /tela para a visualização do jogo, e após isso, basta abrir dois navegadores na mesma hospedagem e os controles já estaram conectados a tela e o jogo poderá ser jogado

Quais tecnologias utilizam?
As tecnologias utilizadas são: HTML, JavaScript, CSS e Socket.IO

Ideia de melhorias?
Adicionar um menu e por meio desse menu adicionar outros modos de jogo, como:

Multiplayer, onde os 2 usuários jogam só por meio do celular sem nenhuma tela distinta

1 jogador, onde um só usuário jogaria contra um BOT

Controle, onde se utiliza a mesma base/modo do PONG atual

Problemas?
O PONG possui diversos bugs e problemas, como por exemplo interferências e delays na comunicação entre o servidor e o cliente, ou seja problemas com o Socket.IO
