### ISSUE TITLE
Criar uma proposta de camiseta

### ISSUE THREAD

**Issue by rafalmeida-ifsp** [fabsoftwareitp/siteFabrica#112]
Criar um modelo de camiseta para a fábrica de software. Cada um cria o seu modelo no software que desejar e após concluir registrar aqui e encaminhar via Discord. A ideia é votar e após a seleção encomendar a confecção para já usarmos no evento IF Casa Aberta.

- Utilizar o logo novo;
- Incluir o nome Fábrica de Software;
- Incluir o logo do IFSP Itapetininga, mas pequeno;
- Usar poucos recursos e cores para não encarecer a confecção (quanto mais elementos mais caro pode ficar a camiseta).

**Comment by maLu70** [comment]
[CamisaPRONTA.pdf](https://github.com/user-attachments/files/16460760/CamisaPRONTA.pdf)

Link para edição do arquivo: https://www.canva.com/design/DAGMPY5-NAs/kXxxWVlDfQYR-WwXpd06yA/edit?utm_content=DAGMPY5-NAs&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by JoniEmann** [comment]
[FabSoftware.pdf](https://github.com/user-attachments/files/16627157/FabSoftware.pdf)

LINK PARA A EDIÇÃO DO ARQUIVO: https://www.canva.com/design/DAGMnix2oPE/zdO0-qF5Q3wJVrHFoX8t6w/edit?utm_content=DAGMnix2oPE&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
