### ISSUE TITLE
Criar cartaz para IFCasaAberta

### ISSUE THREAD

**Issue by rafalmeida-ifsp** [fabsoftwareitp/siteFabrica#116]
**Objetivo:** Criar cartazes atrativos e informativos para os projetos:
- IFAQ nova versão
- SpaceInvaders (atualizado)
- Pong (antigo)

**Público Alvo:** Ensino Fundamental

**Conteúdo dos Cartazes:**

- Sobre o projeto
- Tecnologias envolvidas (explicar sobre)
- Funcionalidades
- Colocar imagens
- Equipe
- Site (escrito)
- QR Code (pra jogar/acessar)

**Modelos:**

* Utilize os modelos de cartazes do Canva como inspiração:
    * https://www.canva.com/search?q=cartaz%20projeto%20
    * https://www.canva.com/search?q=cartaz%20projeto%20informativo%20

**Observações:**

* Mantenha o design dos cartazes limpo, organizado e fácil de ler.
* Utilize cores vibrantes e atraentes para o público do ensino fundamental.
* Adapte a linguagem utilizada para o nível de compreensão do público alvo.

** Distribuição **
- Luma (IFAQ) @maLu70 
- Leo (Pong) @Leo2828 
- Jonny (Space) @JoniEmann 

**Entregáveis**

* Forneça os cartazes em formato digital (JPEG ou PNG) para impressão.
* Inclua o link para o canva direto na issue.

**Comment by Leo2828** [comment]
https://www.canva.com/design/DAGN7OGm-iQ/6BjU75YrcwCuFhFEUo9VmQ/edit?utm_content=DAGN7OGm-iQ&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

![Cartaz Pong(1)](https://github.com/user-attachments/assets/2a4baf11-7fc2-4b05-b557-b6b83cb432f0)

**Comment by JoniEmann** [comment]
![Uploading SPACE INVADERS.png…]()
https://www.canva.com/design/DAGN7Q5QgFM/QylTemwhFhDANJIBaO3tzg/edit?utm_content=DAGN7Q5QgFM&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by JoniEmann** [comment]
https://www.canva.com/design/DAGN7Q5QgFM/QylTemwhFhDANJIBaO3tzg/edit?utm_content=DAGN7Q5QgFM&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

![SPACE INVADERS](https://github.com/user-attachments/assets/a568615b-8294-41e1-9356-2339f743a709)

**Comment by danilocbueno** [comment]
@Leo2828 
 - Ficou só o texto pra verificar e as fontes (uma pro titulo e uma pro texto)
 - Adicionar QRCode do site da Fábrica

**Comment by JoniEmann** [comment]
https://www.canva.com/design/DAGN7Q5QgFM/QylTemwhFhDANJIBaO3tzg/edit?utm_content=DAGN7Q5QgFM&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton



![Image](https://github.com/user-attachments/assets/c0bb280d-5242-40a3-8b5a-8eab5939daae)

**Look how they massacred my boy...**

**Comment by JoniEmann** [comment]
![Image](https://github.com/user-attachments/assets/137aea18-62ba-492b-b702-119a204c7718)

https://www.canva.com/design/DAGN81Qjt0s/cbPS6fStlJ0XgHDy69c9SA/edit?utm_content=DAGN81Qjt0s&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

CARTAZ REDIMENSIONADO PARA A3 COR ROXA

**Comment by JoniEmann** [comment]
![Image](https://github.com/user-attachments/assets/a9cbb6c9-c778-4457-8871-6f6e37305df0)



https://www.canva.com/design/DAGN81Qjt0s/cbPS6fStlJ0XgHDy69c9SA/edit?utm_content=DAGN81Qjt0s&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

CARTAZ REDIMENSIONADO PARA A3 COR AZUL

**Comment by JoniEmann** [comment]
[SPACE INVADERS (1).pdf](https://github.com/user-attachments/files/16629629/SPACE.INVADERS.1.pdf)

VERSÃO PDF A3 REDIMENSIONADO AZUL

**Comment by maLu70** [comment]
[IFAQ-PDFA3.pdf](https://github.com/user-attachments/files/16629964/IFAQ-PDFA3.pdf)
https://www.canva.com/design/DAGN9PAm5gY/s8ltBYsMRNtwGZXPTqKCrw/edit?utm_content=DAGN9PAm5gY&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by rafalmeida-ifsp** [comment]
[IFAQ-A3_20240816_100414_0000.pdf](https://github.com/user-attachments/files/16637388/IFAQ-A3_20240816_100414_0000.pdf)

PDF corrigido pela @maLu70

**Comment by rafalmeida-ifsp** [comment]
![Image](https://github.com/user-attachments/assets/abab593e-bfff-4ad5-a9c3-17e9238670cf)
