### ISSUE TITLE
Desenvolver novo game Brick Breakers

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/siteFabrica#118]
- Desenvolver um jogo novo de breakbreaker
- Fazer pensando direto em celular (Modo retrato)

**Comment by rafalmeida-ifsp** [comment]
Sugestões:

- https://github.com/interborough/brick-breaker-game
- https://github.com/segwuonwu/Brick-Breaker?tab=readme-ov-file
- https://github.com/pctroll/brick-breaker-phaser
- https://github.com/DeveshYadav13/brick-breaker-game

**Comment by danilocbueno** [comment]
- Adicionar tela inicial e final com botões e divs do HTML  e padronização das telas . Usar o exemplo de: (https://discord.com/channels/580808916624080917/1088192776820248626/1281339464152776766)
- Adicionar níveis 
- Adicionar tijolos mais difíceis de quebrar

**Comment by rafalmeida-ifsp** [comment]
- [x] Adicionar animações pontos de mudança de nível;
- [x] Deixar responsivo - Adaptar ao tamanho da tela (estudar: https://github.com/georgedoescode/VBCanvas);
- [x] Implementar sons.
- [x] Resolver problema do loop infinito
- [x] Resolver problema de duplicação da tela final
- [x] Inserir o score e o combo pro lado direito do score
- [x] Fazer um readme para o repo
- [x] Adicionar barras laterais

**Comment by rafalmeida-ifsp** [comment]
Done.
