### ISSUE TITLE
Relatório Setembro

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/siteFabrica#120]
Fazer o relatório do mês seguindo o padrão abaixo. 
Colocar nessa issue como comentário mesmo.

Mês
Semana1
- X Horas: Descrição detalhada do trabalho realizado e links de issues/PR caso tenha.

Semana2
- Y Horas: Descrição detalhada do trabalho realizado e links de issues/PR caso tenha.

Total do mês: X + Y horas
Exemplo:

# Abril

## Semana 14
- 04 horas: Estudo sobre as WebApis: foi estudado como conseguir fazer a implementação da api Screen Orientation para poder travar a orientação do smartphone para o projeto SocketInvaders .
- 06 horas: Implementação da comunicação entre cliente e servidor: foi implementado a nova biblioteca socket.io para comunicação entre cliente e servidor.

## Semana 15
- 04 horas: Estudo sobre as WebApis: foi estudado como conseguir fazer a implementação da api Screen Orientation para poder travar a orientação do smartphone para o projeto SocketInvaders.
- 06 horas: Implementação da comunicação entre cliente e servidor: foi implementado a nova biblioteca socket.io para comunicação entre cliente e servidor.

## Semana 17

Total: X Horas

**Comment by Leo2828** [comment]
# Setembro
## Semana 36

- 5 horas: Continuação da escolha de CMS para o projeto PHILAB.
- 5 horas: Estudo da framework Tina CMS.
- 5 horas: Testes da viabilidade do uso da framework Tina.
- 5 horas: Reunião apresentando os resultados do estudo e testes.

## Semana 37

- 5 horas: Continuação do desenvolvimento da nova versão do jogo pong.
- 5 horas: Reestruturação do Pong.
- 5 horas: Adição de salas e sincronização dos dois players.
- 5 horas: Reunião semanal com resultados e dúvidas sobre o desenvolvimento da nova versão do pong .

## Semana 38

- 5 horas: Continuação do desenvolvimento do Pong com enfoque nas mecânicas.
- 5 horas: Ajustes de bugs no Pong.
- 5 horas: Tentativa de resolução do bug de salas.
- 5 horas: Reunião apresentando o estado da nova versão do Pong.

## Semana 39

- 5 horas: Adição de conteúdo no site do Geek If.
- 5 horas: Ajustes gerais no site do Geek If.
- 5 horas: Continuação da adição de conteúdo e resolução de bugs.
- 5 horas: Reunião apresentando o estado do site do Geek If e subindo-o no ar.

## Semana 40

- 5 horas: Continuação da adição de conteúdo no site do Geek If.

## Total: 85 horas

**Comment by MarcosKauanS** [comment]
# Setembro

## Semana 36
- 01 horas: Resolvido bug de resolução: Foi, arrumado o bug de resolução quando inicia o jogo
- 01 horas: Mudança para o modo portátil: Realizou-se, a mudança para o jogo funcionar no celular somente no modo portátil
- 02 horas: Tentativa de implementar a trava de orientação: Aconteceu, a tentativa de implementar a funcionalidade de trava de orientação

## Semana 37
- 01 horas: Ajustes básicos: Foram, realizados ajustes básicos para melhor legibilidade
- 05 horas: Mudança para funcionar no computador e no celular: Ocorreram, mudanças que permitiu o jogo funcionar no celular e no computador, como adaptações para funcionar com teclado

## Semana 38
- 05 horas: Implementação dos botões em HTML e CSS: Foi, realizado a implementação dos botões utilizando somente HTML e CSS. Sem auxílio do canvas
- 05 horas: Função para o desaparecimento de todos os elementos da tela: Ocorreu, a adição de uma função que faça todos os elementos da tela desaparecer. Dando fullscreen no body e deixando somente o canvas

## Semana 39
- 05 horas: Centralização dos botões na tela: Realizou-se a centralização dos botões na tela e uma tentativa para deixar o código mais limpo
- 01 horas: Ajuste na velocidade da nave: Aconteceu, uma alteração na velocidade da nave para uma melhor experiência
- 02 horas: Responsividade dos botões: Foi, implementado responsividade nos botões
- 03 horas: Festinha de fim de mês: Ocorreu, a festinha que acontece praticamente todos os mêses
## Semana 40
## Total: 31 horas

**Comment by JoniEmann** [comment]
### Setembro

### Semana 36
0 horas

### Semana 37
2 horas: Estudo da base do brick breakers produzido pela Luma, análise do código e da estrutura
3 horas: Pesquisa dos exemplos dado pelo professor Rafael e checagem dos exemplos.

### Semana 38
5 horas: Reunião com a fábrica de software e apresentação dos projetos
2 horas: revisitando o jogo brick breakers para ver estrutura

### Semana 39
2 horas: inicio do ranking do bb, estudos de comparação com o ranking do space
3 horas: tentativa de alocar o ranking do space ao do bb, realizado algumas diferenças
5 horas: reunião com a fábrica, apresentação dos avanços nos projetos
2 horas: pós-reunião, trabalhando nos estudos de fetch, javascript básico, e comandos presentes no ranking

### Semana 40
5 horas: reunião com a fábrica e orientação do Danilo quanto ao ranking, demonstração e explicação dos atributos e sintaxe.
3 horas: estudo da demonstração, mexendo no código e preparando o ranking

### Total: 32 horas
