### ISSUE TITLE
Desenvolvimento de Nova Identidade Visual para o curso de graduação

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/siteFabrica#124]
Desenvolver uma nova identidade visual para o projeto, tomando como referência o conteúdo disponível na página de pós-graduação (https://pos.itp.ifsp.edu.br/#).
Repositorio com as fotos : [Fotos](https://drive.google.com/drive/folders/1FZpHX5PzrW-mpYJcsBBmhPJyKxhBHUwq?usp=sharing).
- [x] Definir paleta de cores, tipografia e elementos visuais.
- [x] Selecionar e integrar as fotos para o design.
- [x] Definir uma cor diferente para dar contraste entre titulos e subtitulos (titulos branco e subtitulo um pouco menos branco)
- [x] Trocar o logo do IF na seção de como ingressar (deixar o logo em escala de cinza)
- [x] Criar um doc com as cores a serem utilizadas e as fontes, procurar manter um padrão entre os espaçamentos e os tamanhos das fontes
- [x] Arrumar a galeria com a memso tamanho das fotos e com as fotos novas (estao na pasta)

**Comment by maLu70** [comment]
https://drive.google.com/drive/folders/12G5pIuy2fHjZe1n9y6eE7sUnaz2xN2rD?usp=sharing
