### ISSUE TITLE
Relatório Outubro

### ISSUE THREAD

**Issue by rafalmeida-ifsp** [fabsoftwareitp/siteFabrica#125]
Fazer o relatório do mês seguindo o padrão abaixo. 
Colocar nessa issue como comentário mesmo.

Mês
Semana1
- X Horas: Descrição detalhada do trabalho realizado e links de issues/PR caso tenha.

Semana2
- Y Horas: Descrição detalhada do trabalho realizado e links de issues/PR caso tenha.

Total do mês: X + Y horas
Exemplo:

# Abril

## Semana 14
- 04 horas: Estudo sobre as WebApis: foi estudado como conseguir fazer a implementação da api Screen Orientation para poder travar a orientação do smartphone para o projeto SocketInvaders .
- 06 horas: Implementação da comunicação entre cliente e servidor: foi implementado a nova biblioteca socket.io para comunicação entre cliente e servidor.

## Semana 15
- 04 horas: Estudo sobre as WebApis: foi estudado como conseguir fazer a implementação da api Screen Orientation para poder travar a orientação do smartphone para o projeto SocketInvaders.
- 06 horas: Implementação da comunicação entre cliente e servidor: foi implementado a nova biblioteca socket.io para comunicação entre cliente e servidor.

## Semana 17

Total: X Horas

**Comment by Leo2828** [comment]
# Outubro
## Semana 40

- 5 horas: Adição de conteúdo na página do Geek-if.
- 5 horas: Reunião apresentando o que foi feito no decorrer da semana.
- 5 horas: Continuação da adição e ajustes no site do Geek-if.

## Semana 41

- 5 horas: Desenvolvimento de uma nova versão do jogo Pong e adição de possibilidade de jogar pelo celular.
- 5 horas: Ajustes e adições no site do Geek-if.
- 5 horas: Continuação de ajustes e resoluções de problemas do Pong, além da tentativa de adicionar salas.
- 5 horas: Reunião apresentando o estado do site do Geek-if e do Pong.

## Semana 42

- 5 horas: Verificações finais e auxilio nas tarefas de outros membros.
- 5 horas: Reunião com discussão e organização sobre o Geek-if
- 10 horas: Evento com apresantação do projeto Fábrica de Software e seus projetos.

## Semana 43

- 5 horas: Retomada da tentativa de adição do Tina CMS.
- 5 horas: Estudo e tentativas de configura o Tina.
- 5 horas: Reunião apresentando o resultado da tentativa de adição do CMS.
- 5 horas: Continuação da configuração do CMS Tina.

## Semana 44

- 5 horas: Prosseguimento com a configuração e adição do Tina.
- 5 horas: Tentativas de configura o framework Astro Js e Tina CMS.
- 5 horas: Adição de conteúdo no novo site sobre o novo curso de graduação do campus.
- 5 horas: Reunião apresentando o que foi realizado no decorrer da semana, atribuição de novas tarefas e treinamento sobre DevOps e docker realizado pelo professor Rafael.

## Total: 95 horas

**Comment by MarcosKauanS** [comment]
# Outubro

## Semana 40
- 05 horas: Mudança na responsividade: Foi realizada uma mudança na responsividade dos botões e na velocidade do tiro do player
- 05 horas: Mudança para uma melhor responsividade: Realizou-se, uma mudança no canvas para uma melhor responsividade
- 01 horas: Adição do rodapé: Ocorreu, a adição do rodapé em html e css

## Semana 41
- 02 horas: Tentativa de resolver bug do canvas: Aconteceu, uma tentativa de resolver o bug que estava ocorrendo com o canvas

## Semana 42
- 03 horas: Responsividade finalizada 1: Houve, uma mudança na responsividade com o intuito de finalizar a mesma
- 01 horas: Teste na responsividade do canvas: Ocorreu, um teste com o intuito de melhorar a responsividade do jogo
- 01 horas: Mudanças básicas: Foram, realizadas mudanças básicas para uma melhor experiência com o site
- 02 horas: Tentativa de resolver bug do cache CSS: Aconteceu uma tentativa para tentar resolver um bug de cache do CSS
- 02 horas: Resolvido gambiarras dos últimos membros: Foi feita mudanças com o intuito de resolver as gambiarras dos  últimos membros
- 06 horas: GEEK-IF: Aconteceu, o GEEK-IF um evento do câmpus voltado para os cosplayers etc... 

## Semana 43
- 0 horas


## Semana 44
- 0 horas

## Total: 28 horas

**Comment by maLu70** [comment]
**Relatório Outubro**

**Semana 40:** 
05 Horas: PHI Lab 
05 Horas: Brick breaker 

**Semana 41:**
05 horas: PHI Lab 

**Semana 42:** 
03 Horas: Finalização do Brick breaker 
04 Horas: PHI Lab 
10 Horas: Geek IF 

**Semana 43:** 
05 horas: Finalização do PHI Lab e readme

Total: 37 Horas
