### ISSUE TITLE
Autoavaliação final Fábrica de Software

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/siteFabrica#134]
Realizar uma autoavaliação individual, refletindo sobre o desenvolvimento do projeto até então e compartilhando suas percepções.

A seguir seguem algumas perguntas que podem nortear a sua autoavaliação. 
**Importante: você não deve fazer no formato de perguntas e respostas. Você deve produzir um texto dissertativo.**

- **Objetivos**: Na sua percepção, em que medida os objetivos da Ação de Ensino foram atingidos?
- **Desenvolvimento dos Projetos**: Como você avalia o desenvolvimento dos projetos da Ação? Quais foram os maiores desafios e conquistas que você vivenciou?
- **Metodologia**: A metodologia utilizada na Ação foi eficaz para você? Quais pontos fortes e fracos você identificou?
- **Comunicação e Trabalho em Equipe**: Como você avalia a comunicação e o trabalho em equipe durante a Ação?
- **Aprendizagem**: Quais foram os principais aprendizados que você obteve durante a Ação?
- **Sugestões**: Quais sugestões você tem para melhorar a Ação de Ensino em futuras edições?

**Entregáveis:**
- Produzir um texto dissertativo com a sua autoavaliação individual do projeto.
- Incorporar o texto na issue em formato de comentário.
- Data: até dia 11/12

**Comment by Leo2828** [comment]
A fábrica de software é uma ação de ensino que tem como objetivos propiciar um ambiente similar a um profissional para permitir que os envolvidos no projeto consigam desenvolver um crescimento pessoal e profissional. Durante todo o período que atuei como bolsista consegui ter uma noção clara de como é a área profissional e obtive habilidades que vão me auxiliar não somente na minha carreira, mas também no meu dia a dia. Dentre essas habilidades, posso citar um aprimoramento na minha forma de pensar que foi desenvolvida graças a diversas tarefas e problemas que foram discutidos e resolvidos durante o ano. Outra aptidão que consegui otimizar substancialmente foi a minha base de conhecimento técnico que não somente abrange linguagens de programação, mas também frameworks, que antes da minha entrada no projeto eu não possuía nenhum conhecimento. Quanto a comunicação e trabalho em equipe, por mais que eu tenha trabalhado sozinho na maioria dos projetos, ainda sim consegui desenvolver minha comunicação graças às reuniões semanais e projetos que ajudei e fui ajudado.
A metodologia do projeto, que é semelhante a um ambiente de trabalho, é definida da seguinte forma: um projeto é atribuído aos membros da equipe e durante todo o desenvolvimento do projeto, o progresso, dificuldades e descobertas são discutidos entre todos os membros. Esse procedimento permite um desdobramento ágil e eficiente, e, para mim, funcionou muito bem. Diversos projetos foram realizados dessa forma no decorrer do ano, alguns eu consegui finalizar sem dificuldades, outros tive dificuldades, porém todas essas experiências foram cruciais para o meu crescimento.
Eu não possuo nenhuma sugestão em relação ao melhoramento da Ação de Ensino, acredito que ela não somente cumpre seu objetivo perfeitamente, mas também vai além e promove um ambiente que não somente aperfeiçoa qualidades relacionadas a área de informática, mas também promove um crescimento pessoal.

**Comment by JoniEmann** [comment]
Tendo se passado todo esse tempo na fábrica de software é denotável como ela é uma parte e um projeto totalmente diferente apresentado nos cursos de informática oferecidos pelo Campus Itapetininga, eu tenho visto a dificuldade e a responsabilidade que é estar num projeto desses, não é fácil, apesar dos pesares também vivenciei uma experiência nova e que mostrou que minhas capacidades não são tão hábeis, na verdade, a fábrica me mostrou que sempre tem espaço para melhorar; os ensinos os objetivos foram difíceis, é um projeto difícil de se acompanhar quando se faz um curso no campus em conjunto. A fábrica de software conseguiu entregar o que queria no ano de 2024, sites, atualizações e principalmente otimizações - cujo, uma atualização denotável, é o próprio site da fábrica e o salto de tecnologias utilizadas pelos participantes dela - e mesmo que difícil, os professores estão lá para te orientar sobre o que fazer nas reuniões e bom, se deve valorizar muito.
	Enfrentando diversos desafios, é possível confiar nos colegas da fábrica, os projetos as quais eu participei em conjunto trouxeram trabalhos únicos e coesos, ideias compartilhadas que depois aceitas pelos professores, além de que, os professores se comprometem a trazer um ensino adicional ao projeto como a visita ao SESI e a conversa com os participantes veteranos e as orientações sobre design, aprendendo sobre isso e que, novamente, a fábrica é algo que precisa de responsabilidade. Porém, junto de todos os fatos, sempre há coisas a melhorar, o norteamento dos participantes apesar de serem bons nas reuniões, são ideias estritas sobre o que fazer em relação ao projeto, ou seja, se o desenvolvedor daquele projeto ter tarefas, ele terá de pesquisar por si mesmo aquela tecnologia; no inicio da fábrica quando os projetos eram mais simples, os professores disponibilizaram documentos sobre a base de CSS E HTML, isso foi um diferencial, pois, já saberíamos como mexer, no que mexer e onde mexer - ao entender a lógica do projeto - contudo, não sendo disponibilizado uma documentação ou introdução ao JavaScript, não pude entender direito o que estava acontecendo e quando fui perceber, me vi dependente de meus colegas.
	Por fim, a fábrica num geral traz diversas experiências sim, mas o aluno tem que estar psicologicamente preparado e ter noção mais aprofundada de como vai ser, e que as vezes você não vai ter um ombro amigo pois você estará num projeto diferente, e que as orientações são importantíssimas para a fábrica pois, sem os professores, o rendimento iria decair, portanto, os professores interagirem, as ferramentas de comunicação como o github e o discord tem que ser utilizadas desde o inicio, mantendo uma fábrica estável e de bom rendimento.

**Comment by JoniEmann** [comment]
Tendo se passado todo esse tempo na fábrica de software é denotável como ela é uma parte e um projeto totalmente diferente apresentado nos cursos de informática oferecidos pelo Campus Itapetininga, eu tenho visto a dificuldade e a responsabilidade que é estar num projeto desses, não é fácil, apesar dos pesares também vivenciei uma experiência nova e que mostrou que minhas capacidades não são tão hábeis, na verdade, a fábrica me mostrou que sempre tem espaço para melhorar; os ensinos os objetivos foram difíceis, é um projeto difícil de se acompanhar quando se faz um curso no campus em conjunto. A fábrica de software conseguiu entregar o que queria no ano de 2024, sites, atualizações e principalmente otimizações - cujo, uma atualização denotável, é o próprio site da fábrica e o salto de tecnologias utilizadas pelos participantes dela - e mesmo que difícil, os professores estão lá para te orientar sobre o que fazer nas reuniões e bom, se deve valorizar muito. 
Enfrentando diversos desafios, é possível confiar nos colegas da fábrica, os projetos as quais eu participei em conjunto trouxeram trabalhos únicos e coesos, ideias compartilhadas que depois aceitas pelos professores, além de que, os professores se comprometem a trazer um ensino adicional ao projeto como a visita ao SESI e a conversa com os participantes veteranos e as orientações sobre design, aprendendo sobre isso e que, novamente, a fábrica é algo que precisa de responsabilidade. Porém, junto de todos os fatos, sempre há coisas a melhorar, o norteamento dos participantes apesar de serem bons nas reuniões, são ideias estritas sobre o que fazer em relação ao projeto, ou seja, se o desenvolvedor daquele projeto ter tarefas, ele terá de pesquisar por si mesmo aquela tecnologia; no inicio da fábrica quando os projetos eram mais simples, os professores disponibilizaram documentos sobre a base de CSS E HTML, isso foi um diferencial, pois, já saberíamos como mexer, no que mexer e onde mexer - ao entender a lógica do projeto - contudo, não sendo disponibilizado uma documentação ou introdução ao JavaScript, não pude entender direito o que estava acontecendo e quando fui perceber, me vi dependente de meus colegas. 
Por fim, a fábrica num geral traz diversas experiências sim, mas o aluno tem que estar psicologicamente preparado e ter noção mais aprofundada de como vai ser, e que as vezes você não vai ter um ombro amigo pois você estará num projeto diferente, e que as orientações são importantíssimas para a fábrica pois, sem os professores, o rendimento iria decair, portanto, os professores interagirem, as ferramentas de comunicação como o github e o discord tem que ser utilizadas desde o inicio, mantendo uma fábrica estável e de bom rendimento.

**Comment by MarcosKauanS** [comment]
A Fábrica de software, tem como objetivo simular um ambiente profissional. O objetivo da ação de ensino, foi altamente atingido, no tempo, em que estive na fábrica, percebi melhoras em vários dos meus aspectos pessoais. Entre eles, comunicação; Todas as quintas, realizamos uma reunião para discutir sobre melhoras nos projetos antigos e adição de novos, trabalho em equipe; Ao longo de vários projetos, tive vários desafios e duplas que me ajudaram.
O desenvolvimento dos projetos está sempre sendo inspecionado pelos professores, onde caso a gente precise de ajuda, eles param para nos ouvir e nos auxiliam para achar a solução do problema. Isso e outros aspectos fazem com que ele seja o melhor possível.
No decorrer da fábrica, enfrentei muitos desafios e obtive várias conquistas. Um dos meus maiores desafios foi a adaptação ao utilizar o JavaScript, a maior conquista que adquiri foi finalizar vários projetos, a sensação de você terminar algo, de se sentir realizado e que pode fazer de tudo. Participei de vários projetos e pude ter uma boa noção de como funciona um ambiente empresarial, também desenvolvi uma base sólida da programação e outros.
A metodologia utilizada, tem um ótimo desempenho por conta das reuniões e administração dos professores. Em minha opinião, não tenho nenhuma sugestão para a melhora na ação de ensino
