### ISSUE TITLE
Treinamento Laravel

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/siteFabrica#18]
Criar uma documentação (slides) para treinamento sobre a Tecnologia Laravel.

- Fazer atividade para que os novos integrantes possam replicar o conceito nos computadores da fábrica;

Tópicos a serem abordados no treinamento:
- criação de ROTAS
- uso dos templates com BLADE (diretivas if, else, auth, guest ...)
- arquitetura MVC (Model, View, Controller)
- migrations

Atividades
- Criar uma rota nova em um projeto do zero;
- Criar um layout e usar com o blade;
- Criar uma migration;
- Criar um controller e um model;

**Comment by andreaugusto-sourc** [comment]
[treinamento_fab.docx](https://github.com/fabsoftwareitp/fabsoftware.itp.ifsp.edu.br/files/11035160/treinamento_fab.docx)
Finalizada as instruções das atividades para o treinamento de Laravel .

**Comment by danilocbueno** [comment]
Para criar um PR e finalizar a issue, criar um documento MD com um tutorial sobre a atividade proposta para o treinamento.
