### ISSUE TITLE
Acesso ao usuário do git nas máquinas da Fábrica

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/siteFabrica#28]
Atualmente é necessário fazer uma alteração manual dos usuário do git para as máquinas da fábrica, visto que as mesmas são compartilhadas por diversos membros.
Verificar como usar contas diferentes na mesma máquina

**Comment by rafalmeida-ifsp** [comment]
Resolvido com o ingresso dos computadores no domínio e perfil de usuário individualizado.
