### ISSUE TITLE
Analisar projeto IFAQ

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/siteFabrica#45]
Como conversamos um dos projetos do casa aberta é o IFAQ desenvolvido pelo @andreaugusto-sourc.

Preciso que vocês se apropriem do projeto, ou seja, baixem, testem, e entendam o código. Além disso temos algumas melhorias que precisamos fazer antes do final. Podem se dividir como quiserem.

Necessário:
- criar um README.me para explicar um pouco sobre o projeto
- a ideia é manter apenas uma pergunta na tela de cada vez e fazer como se fosse um slider (https://swiperjs.com/) na ideia dessa biblioteca para que quem está utilizando possa ir passando as perguntas com o movimento de swipe (dedo para o lado).
- pensar em possíveis melhorias que possamos fazer
- apresentar as ideias/melhorias na próxima reunião
- o repo está com em https://github.com/andreaugusto-sourc/ifaq

**Comment by danilocbueno** [comment]
@andreaugusto-sourc por favor faça a transferência do projeto pra organização fabsoftwareitp

**Comment by andreaugusto-sourc** [comment]
pronto!
