### ISSUE TITLE
Fazer post sobre o IFCasaAberta

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/siteFabrica#51]
Criar um texto para postar no site da Fábrica sobre a participação da fábrica no evento casa aberta.

O texto deve conter uma explicação sobre as aplicações que foram desenvolvidas especificamente para o evento. Para cada aplicação:
- proposta da aplicação
- objetivo
- tecnologias utilizadas
- funcionalidades
- prints de tela 

Falar também sobre os integrantes que participaram e das outras aplicações mas de maneira simplificada e adicionar fotos do da participação da Fábrica. As fotos estão no drive da fábrica.

**Comment by rafalmeida-ifsp** [comment]
Done.
