### ISSUE TITLE
Estudar sobre o projeto IFAC

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/siteFabrica#78]
# Semana 1
- Estudar o projeto IFAC (https://github.com/fabsoftwareitp/ifaq.fabsoftware.itp.ifsp.edu.br)
- Tentar responder as perguntas: o que é? para que serve? como usar? Quais tecnologias utilizam? Ideia de melhorias? Problemas?
- Fazer uma apresentação sobre o que aprendeu para apresentar aos demais membros do grupo na próxima semana.

# Semana 2
@maLu70 
- Pesquisar sobre como criar videos baseados em pessoas famosas/personagens com IA para ler texto. Tentar trazer exemplos.

@MarcosFabSoftware 
- Pesquisar sobre WebStories: o que é? Como utilizar? Como criar? Como incorporar em uma página ou mesmo utilizar em uma página. Tentar trazer exemplos.

# Semana 3

@JoniEmann @MarcosFabSoftware 
- Estudar CSS (introdução, seletores, propriedades inicias texto, background)
- Estudar documentação WebStories (https://amp.dev/documentation/guides-and-tutorials/stories/start/visual_story/)
- Apresentação: 
  - Fazer uma apresentação sobre o que aprendeu - SEM LER
  - Treinar antes de fazer a apresentação (no máximo 15min)
 
@maLu70 
- Investigar Imagem/Video para as perguntas e legendas
- Trocar a linguagem das perguntas/respostas para uma mais coloquial/informal/jovial

**Comment by MarcosFabSoftware** [comment]
Oque é?
A sigla FAQ refere-se, a um documento, geralmente construído no formato de perguntas e respostas, contendo dúvidas recorrentes sobre um determinado assunto. Com isso, podemos identificar que a sigla IFAQ é um jogo de palavras com IF e FAQ, então IFAQ é um documento de perguntas e respostas do Instituto Federal de São Paulo câmpus Itapetininga.

Para que serve?
O projeto IFAQ, é um projeto do Instituto Federal de São Paulo câmpus Itapetininga, que tem como objetivo responder as principais perguntas dos estudantes que pretendem estudar no Instituto Federal.

Como usar?
Primeiramente acesse o site IFAQ, com o domínio "ifaq.fabsoftware.itp.ifsp.edu.br", após isso clique em "Ir para as perguntas". Assim, é só clicar nas perguntas que uma "voz robótica" vai responder narrando a pergunta e sua resposta, para ir para a próxima pergunta ou retroceder é só clicar nas setas.

Quais tecnologias utilizam?
As tecnologias que o site IFAQ utiliza são: Viewport Meta, Iphone / Mobile Compatible, nginx, UTF-8, HTML5, X-UA-Compatible, CSS, WebP e Javascript Defer.
 
Ideia de melhorias?
1- Modificar a "voz" para parecer menos robótica.
2- Abreviar a frase Instituto Federal de São Paulo campûs Itapetininga ou omiti-la, trocando por pronomes, pois ela é muito repetitiva.

Problemas?
1- A "voz" é muito robótica
2- A frase Instituto Federal de São Paulo campûs Itapetininga é muito repetiviva, irritando um pouco.

*Oque mais posso melhorar chefe?*

**Comment by danilocbueno** [comment]
@maLu70 
- permitir uma opção de leitura sem o som (atualmente não é possível somente ler a resposta, tem que ter o audio)
- botão ligue e clique está com a ideia incorreta (não marca nada que tem que clicar na pergunta)

**Comment by MarcosFabSoftware** [comment]
O que é WebStories?
Os WebStories são: Uma versão web para os stories já conhecidos, também são uma maneira inteligente de criar páginas com narrativas visuais, voltadas especialmente para o público em dispositivos móveis. Utilizam conteúdos de imagem curtos, de preferência vídeos, que podem vir acompanhados de legenda e trilha sonora e fazem sucesso na internet.

O conteúdo é exibido em forma de slides, estimulando a visualização de mais conteúdos, já que cada story dura em geral alguns segundos. Por meio deles, você pode exibir aos usuários do Google informações fáceis e rápidas de se consumir.


Como utilizar?
Pode-se utilizar diversas ferramentas para isso, desenvolvidas por terceiros credenciados pelo Google e integrantes do projeto AMP.

Porém, o formato mais comumente utilizado para criar e gerir Web Stories é por meio do plugin para o WordPress.

Vantagens?
Uma das principais vantagens em usar Web Stories é publicar conteúdo de forma objetiva, imersiva e visualmente bastante atraente. Com apenas alguns slides é possível criar tutoriais, divulgar dados, promover produtos e serviços e muito mais.

Ele foi projetado para o consumo em smartphones. Portanto, é isso que faz com que o design do conteúdo seja responsivo e atraente para os usuários.

O Web Stories traz layouts prontos, bonitos e flexíveis que podem ser adaptados à sua marca.

Como mencionado, o Google Web Stories ajuda a aumentar o tráfego do seu site. Com ele, seu site pode aparecer no topo dos resultados de diversos produtos Google, como Pesquisa, Imagens, Discover e também no Google App.


Como criar?
1- Escolha um tema envolvente para a sua história.
2- Decida qual narrativa visual irá capturar melhor a atenção do seu público.
3- Utilize a ferramenta de criação do Google Web Stories para começar.
4- Importe imagens, vídeos e sons que complementem o seu conteúdo.
5- Organize-os em sequência lógica, garantindo fluxo e coerência na narrativa.
6- Adicione textos breves e claros para transmitir informações – chave.
7- Inclua elementos interativos, como enquetes ou quizzes, para engajar os espectadores.
8- Pense na experiência do usuário: torne cada slide fácil de ler e navegar.
9- Verifique se sua Web Story está seguindo as práticas recomendadas pelo Google.
10- Insira metadados adequados para ajudar no desempenho da busca orgânica.
11- Teste sua Web Story em diferentes dispositivos móveis para garantir compatibilidade total.
12- Publique – a no seu site ou através de plataformas parceiras permitidas pelo AMP válido.

Vamos para o exemplo!
AMP-Stories

**Comment by JoniEmann** [comment]
WebStories

* O que é?
WebStories é uma plataforma do Google cujo funciona como se fosse um fast-content, a qual funciona num estilo parecido do Instagram porém sendo colocados em páginas/sites únicos, sendo perceptível os seus conteúdos diversos que abordam propagandas, notícias, informações e etc.
	WebStories também pode ser visto como um site que permite você conhecer e observar outros temas, sendo visto o que está nas trendings.

* Como utilizar?
Uma forma de utilizar o WebStories é para gerar tráfego e ganhar uma renda deste tráfego, ou, para compartilhar informações rápidas, perguntas e respostas ou para crescer no âmbito de conhecimento web, fazendo e-marketing e dentre outras formas de utilizações pessoais. 

* Como criar?
Para criar um WebStories, você inicialmente precisa de uma ferramenta ou software para que você possa sequer iniciar, sendo dentre elas a do próprio Google, WordPress(extensão), Hostinger e etc.
		Em primeiro lugar você precisa do seu conteúdo, a qual você vai abordar e trabalhar dentre o layout da webstories, após ter pegado seu conteúdo e ter pegado o tema a qualquer será abordado, você pega uma das ferramentas disponíveis e inicia a criação.

Você poderá implementar vídeos, elementos sólidos, gifs(Não recomendado) e etc. Sendo que, para otimizar seu webstories é necessário não sobrecarregar com caracteres ou não jogar muitas informações e letras na tela do usuário que está vendo o conteúdo.
...
		Tendo feito todo o conteúdo e organizado, adicionado os recursos de acessibilidade, chegando o momento de postagem, é necessário que você entre na plataforma AMP ou do Google Pará que você possa postar seu webstories, e também enviá-lo num formato.

Sendo recomendável após a pastagem, salvar os stories em formato "Index".

**Comment by MarcosFabSoftware** [comment]
https://github.com/fabsoftwareitp/fabsoftware.itp.ifsp.edu.br/issues/78#issue-2226262734
- 04 horas: Estudo do site IFAQ: Foi estudado o site e respondido as perguntas relacionadas, oque é? para que serve? como usar? Quais tecnologias utilizam? Ideias de melhorias? Problemas? E foi realizada uma apresentação sobre oque foi estudado
- 04 horas: Estudo de WebStories: Foi estudado sobre WebStories e respondido as perguntas, o que é? Como utilizar? Como criar? Como incorporar em uma página ou mesmo utilizar em uma página? E apresentação de exemplos
